apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-app
  labels:
    team: cypress
spec:
  replicas: 1
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      name: good-app
      team: cypress
  template:
    metadata:
      labels:
        name: good-app
        team: cypress
    spec:
      containers:
      - name: main
        image: nginx
        env:
        - name: APP_VER
          value: "2"
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -cx
              - |
                echo "{\"host\":\"$HOSTNAME\", \"ver\":\"$APP_VER\"}" > /usr/share/nginx/html/index.html
